pombola/core/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.views.generic import TemplateView, ListView, RedirectView

from pombola.core import models
from pombola.core.views import (HomeView, PlaceDetailView,
    OrganisationList, OrganisationKindList, PlaceKindList, PersonDetail,
    PersonDetailSub, PlaceDetailSub, OrganisationDetailSub,
    OrganisationDetailView, HelpApiView)

person_patterns = patterns('pombola.core.views',
    url(r'^all/',
        ListView.as_view(model=models.Person),
        name='person_list'),

    url(
        r'^politicians/',
        # This is what I'd like to have - but as the 'position' path does
        # not exist yet it gets confused. Hardcode instead - this end point
        # should be removed at some point - legacy from the MzKe site.
        # 'url': reverse('position', kwargs={'slug':'mp'}),
        RedirectView.as_view(url='/position/mp', permanent=True),
    ),

    # featured person ajax load
    url(r'^featured/((?P<direction>(before|after))/)?(?P<current_slug>[-\w]+)',
        'featured_person',
        name='featured_person'),

    url(r'^(?P<slug>[-\w]+)/$', PersonDetail.as_view(), name='person'),

  )

for sub_page in ['scorecard', 'comments', 'experience', 'appearances', 'contact_details']:
    person_patterns += patterns(
        'pombola.core.views',
        url(
            '^(?P<slug>[-\w]+)/%s/' % sub_page,
            PersonDetailSub.as_view(sub_page=sub_page),
            name='person_%s' % sub_page,
        )
    )

if settings.ENABLED_FEATURES['bills']:
    person_patterns += patterns(
        'pombola.core.views',
        url(
            '^(?P<slug>[-\w]+)/bills/',
            PersonDetailSub.as_view(sub_page='bills'),
            name='person_bills',
        )
    )



place_patterns = patterns('pombola.core.views',

    url( r'^all/', PlaceKindList.as_view(), name='place_kind_all' ),
    url( r'^is/(?P<slug>[-\w]+)/$', PlaceKindList.as_view(), name='place_kind'     ),
    url( r'^is/(?P<slug>[-\w]+)/(?P<session_slug>[-\w]+)/?', PlaceKindList.as_view(), name='place_kind'     ),

    url(r'^(?P<slug>[-\w]+)/$',
        PlaceDetailView.as_view(),
        name='place'),

    # redirect .../candidates to .../aspirants so that the URL wording matches
    # that on the site. This is to fix originally using the word 'candidates'
    # and can probably be removed at some point when there are no more hits on
    # this path - after July 2013 feels about right.
    url(
        r'^(?P<slug>[-\w]+)/candidates/$',
        RedirectView.as_view(url='/place/%(slug)s/aspirants', permanent=True),
    ),
)

for sub_page in ['aspirants', 'election', 'scorecard', 'comments', 'people', 'places', 'organisations', 'data', 'projects', 'budgets']:
    place_patterns += patterns(
        'pombola.core.views',
        url(
            '^(?P<slug>[-\w]+)/%s/' % sub_page,
            PlaceDetailSub.as_view(sub_page=sub_page),
            name='place_%s' % sub_page,
        )
    )


organisation_patterns = patterns('pombola.core.views',
    url(r'^all/', OrganisationList.as_view(), name='organisation_list'),
    url(r'^is/(?P<slug>[-\w]+)/', OrganisationKindList.as_view(), name='organisation_kind'),
    url(r'^(?P<slug>[-\w]+)/$', OrganisationDetailView.as_view(), name='organisation'),
)

for sub_page in ['comments', 'contact_details', 'people']:
    organisation_patterns += patterns(
        'pombola.core.views',
        url(
            '^(?P<slug>[-\w]+)/%s/' % sub_page,
            OrganisationDetailSub.as_view(sub_page=sub_page),
            name='organisation_%s' % sub_page,
        )
    )

urlpatterns = patterns('pombola.core.views',
    # Homepage
    url(r'^$', HomeView.as_view(), name='home'),

    (r'^person/', include(person_patterns)),
    (r'^place/', include(place_patterns)),
    (r'^organisation/', include(organisation_patterns)),

    url(r'^position/(?P<pt_slug>[-\w]+)/$', 'position_pt', name='position_pt'),
    url(r'^position/(?P<pt_slug>[-\w]+)/(?P<ok_slug>[-\w]+)/$', 'position_pt_ok', name='position_pt_ok'),
    url(r'^position/(?P<pt_slug>[-\w]+)/(?P<ok_slug>[-\w]+)/(?P<o_slug>[-\w]+)/$', 'position_pt_ok_o', name='position_pt_ok_o'),

    # specials
    url(r'^parties', 'parties', name='parties'),

    # Ajax select
    url(r'^ajax_select/', include('ajax_select.urls')),
)

urlpatterns += patterns('pombola.core.views',
    url(r'^status/memcached/',       'memcached_status', name='memcached_status'),
)

if settings.POPIT_API_URL:
    # Add the dynamically generated API help page
    urlpatterns.append(
        url(r'^help/api', HelpApiView.as_view(), name='help-api')
    )

# Make it easy to see the various error pages without having to fiddle with the
# STAGING settings.
urlpatterns += patterns('',
    url(r'^status/down/', TemplateView.as_view(template_name='down.html') ),
    url(r'^status/404/',  TemplateView.as_view(template_name='404.html') ),
    url(r'^status/500/',  TemplateView.as_view(template_name='500.html') ),
)


# We handle the robots here rather than as a static file so that we can send
# different content on a staging server. We don't use direct_to_template as we
# want to set some caching headers too.
urlpatterns += patterns('pombola.core.views',
    url(r'robots.txt', 'robots' ),
)

pombola/hansard/urls.py
from django.conf.urls import patterns, include, url
from pombola.hansard.views import IndexView, SittingView, PersonAllAppearancesView

urlpatterns = patterns('pombola.hansard.views',
    url( r'^$', IndexView.as_view(), name="index" ),

    # not the final URL structure - but something to start work with
    # url( r'^sitting/(?P<pk>\d+)/', SittingView.as_view(), name="sitting_view" ),

    # Try to make the url human readable
    # sitting/<venue>/<start_date>[-<start_time>]/
    # sitting/main_chamber/2011-12-03
    # sitting/main_chamber/2011-12-03-14-00-00
    url(
        r'^sitting/(?P<venue_slug>[\w\-]+)/(?P<start_date_and_time>\d{4}-\d{2}-\d{2}(?:-\d{2}-\d{2}-\d{2})?)',
        SittingView.as_view(),
        name="sitting_view"
    ),



    # views for a specific person
    url( r'^person/(?P<slug>[\w\-]+)/summary/', 'person_summary', name='person_summary' ),
    # url( r'^person/(?P<slug>[\w\-]+)/',         'person_entries', name='person_entries' ),

    # 'Show All' page for a specific person
    url(
        r'^person/(?P<slug>[\w\-]+)/appearances/',
        PersonAllAppearancesView.as_view(),
        name='person_appearances_all',
    )

)

pombola/kenya/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from pombola.kenya.views import KEPersonDetail, KEPersonDetailAppearances

from .views import (CountyPerformanceView, CountyPerformanceSenateSubmission,
    CountyPerformancePetitionSubmission, CountyPerformanceShare,
    CountyPerformanceSurvey, EXPERIMENT_DATA, ThanksTemplateView,
    ShujaazFinalistsView
)

urlpatterns = patterns('',
    url(r'^shujaaz$', ShujaazFinalistsView.as_view(), name='shujaaz-finalists'),
    url(r'^shujaaz-voting$', TemplateView.as_view(template_name='shujaaz-voting.html'), name='shujaaz-voting'),
    url(r'^intro$',                TemplateView.as_view(template_name='intro.html') ),
    url(r'^register-to-vote$',     TemplateView.as_view(template_name='register-to-vote.html') ),
    url(r'^find-polling-station$', TemplateView.as_view(template_name='find-polling-station.html') ),
    url(r'^person/(?P<slug>[-\w]+)/$',
        KEPersonDetail.as_view(), name='person'),
    url(r'^person/(?P<slug>[-\w]+)/appearances/$',
        KEPersonDetailAppearances.as_view(sub_page='appearances'),
        name='person'),
)

# Create the two County Performance pages:

for experiment_slug in ('mit-county', 'mit-county-larger'):
    base_name = EXPERIMENT_DATA[experiment_slug]['base_view_name']
    base_path = r'^' + base_name
    view_kwargs = {'experiment_slug': experiment_slug}
    urlpatterns.append(
        url(base_path + r'$',
            CountyPerformanceView.as_view(**view_kwargs),
            name=base_name)
    )

    for name, view in (
        ('senate', CountyPerformanceSenateSubmission),
        ('petition', CountyPerformancePetitionSubmission)):

        urlpatterns += (
            url(base_path + r'/{0}$'.format(name),
                view.as_view(**view_kwargs),
                name=(base_name + '-{0}-submission'.format(name))),
            url(base_path + r'/{0}/thanks$'.format(name),
                ThanksTemplateView.as_view(
                    base_view_name=base_name,
                    template_name=('county-performance-{0}-submission.html'.format(name))
                )),
        )

    urlpatterns += (
        url(base_path + r'/share',
            CountyPerformanceShare.as_view(**view_kwargs),
            name=(base_name + '-share')),
        url(base_path + r'/survey',
            CountyPerformanceSurvey.as_view(**view_kwargs),
            name=(base_name + '-survey')),
    )

pombola/urls.py
import re

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = []


# Country app. In order to let the country app inject its own pages we list it
# first and send all urls through it. If it does not match anything routing
# continues as normal.
#
# Note that anything the country app catches it has to actually process, Django
# does not appear to support fallthrough from controllers:
# http://stackoverflow.com/questions/4495763/fallthrough-in-django-urlconf
if settings.COUNTRY_APP:
    urlpatterns += patterns('',
        (r'^', include('pombola.' + settings.COUNTRY_APP + '.urls')),)

# Needs to occur _before_ admin.autodiscover()
import autocomplete_light
autocomplete_light.autodiscover()

# Admin section
from django.contrib import admin
admin.autodiscover()

from ajax_select import urls as ajax_select_urls
urlpatterns += patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete_light/', include('autocomplete_light.urls')),
)

# mapit
urlpatterns += patterns('',
    (r'^mapit/', include('mapit.urls')),
)

# Info pages
urlpatterns += patterns('',
    (r'^info/', include('pombola.info.urls.pages')),
    (r'^blog/', include('pombola.info.urls.blog')),
)

# File archive
urlpatterns += patterns('',
    (r'^file_archive/', include('pombola.file_archive.urls')),
)

# SayIt - speeches
#if settings.ENABLED_FEATURES['speeches']:
#    urlpatterns += patterns('',
#        (r'^speeches/', include('speeches.urls', namespace='speeches', app_name='speeches-default')),
#    )

# Hansard pages
if settings.ENABLED_FEATURES['hansard']:
    urlpatterns += patterns('',
        (r'^hansard/', include('pombola.hansard.urls', namespace='hansard', app_name='hansard')),
    )

# Project pages
if settings.ENABLED_FEATURES['projects']:
    urlpatterns += patterns('',
        (r'^projects/', include('pombola.projects.urls')),
    )

# ajax preview of the markdown
urlpatterns += patterns('',
    url(r'^markitup/', include('markitup.urls'))
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# needed for the selenium tests.
if settings.IN_TEST_MODE:
    static_url = re.escape(settings.STATIC_URL.lstrip('/'))
    urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % static_url, 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

# search
urlpatterns += patterns('',
    (r'^search/', include('pombola.search.urls')),
)

# feedback
urlpatterns += patterns('',
    (r'^feedback/', include('pombola.feedback.urls')),
)

# map
urlpatterns += patterns('',
    (r'^map/', include('pombola.map.urls')),
)

# votematch
if settings.ENABLED_FEATURES['votematch']:
    urlpatterns += patterns('',
        (r'^votematch/', include('pombola.votematch.urls')),
    )


# # spinner - uncomment if needed. Not needed just to display spinner on the
# # homepage using carousel.
# if settings.ENABLED_FEATURES['spinner']:
#     urlpatterns += patterns('',
#         (r'^spinner/', include('pombola.spinner.urls')),
#     )

# bills
if settings.ENABLED_FEATURES['bills']:
    urlpatterns += patterns('',
        (r'^bills/', include('pombola.bills.urls', namespace='bills', app_name='bills')),
    )


# Everything else goes to core
urlpatterns += patterns('',
    (r'^', include('pombola.core.urls')),
)

# For South Africa, we need SayIt to catch any otherwise unmatched
# URLs, so this has to come last:
if settings.COUNTRY_APP and settings.COUNTRY_APP == 'south_africa':
    urlpatterns += patterns('',
        (r'^', include('pombola.south_africa.fallback_urls')),)

pombola/kenya/models.py
from django.db import models

# Create your models here.

pombola/kenya/forms.py
from django import forms
from django.forms.widgets import Textarea


class CountyPerformancePetitionForm(forms.Form):
    name = forms.CharField(
        error_messages={'required': 'You must enter a name'},
        widget=forms.TextInput(
            attrs={
                'required': 'required',
                'placeholder': 'Your name'}))
    email = forms.EmailField(
        error_messages={'required': 'You must enter a valid email address'},
        widget=forms.TextInput(
            attrs={
                'required': 'required',
                'placeholder': 'Your email address'}))

    def clean(self):
        # We want to provide a single helpful error message if both
        # name and email address aren't supplied, so override clean to
        # detect that condition
        cleaned_data = super(CountyPerformancePetitionForm,
                             self).clean()
        if not cleaned_data:
            raise forms.ValidationError(
                "You must specify a name and a valid email address")
        return cleaned_data


class CountyPerformanceSenateForm(forms.Form):
    comments = forms.CharField(
        label='Tell the senate what would like to see in your county',
        error_messages={'required': "You didn't enter a comment"},
        widget=Textarea(
            attrs={
                'rows': 5,
                'cols': 60,
                'required': 'required',
                'placeholder': 'Add any comments here'}))

pombola/kenya/templates/core/object_base.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ object.name }}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block page %}
    <div id="page" class="object-base clearfix">

        {% include "disqus_javascript.html" %}

        <div class="object-header">

            <div class="object-sidebar">
                {% block profile_pic %}
                  <div class="profile-pic">
                      {% thumbnail object.primary_image "210x210" crop="center" as im %}
                      <img src="{{ im.url }}" alt="{{ object.name }}" width="{{ im.width }}" height="{{ im.height }}" />
                      {% empty %}
                      <img src="{{STATIC_URL}}images/{{object.css_class}}-210x210.jpg" />
                      {% endthumbnail %}
                  </div>
                {% endblock %}

                <div class="profile-info" id="hfProfileInfo">
                  {% block profile_info %}
                  {% endblock %}
                </div>
            </div>

            <div class="object-titles">
                {% block object_title %}
                  <h1>{{ object.title }} {{ object.name }}</h1>
                {% endblock %}

                {% block object_tagline %}{% endblock %}

                {% include 'core/social_tools.html' %}

                {% block object_menu %}
                <div class="object_menu">
                  <nav>
                    <ul>
                      {% block object_menu_links %}
                      {% endblock %}
                    </ul>
                  </nav>
                </div>
                {% endblock %}
            </div>

        </div>

        <div class="object-detail">
            <div class="object-detail-inner">
                <div class="large-container">
                  {% block subcontent %}
                    You should add your own custom content to this layout in a 'subcontent' block.
                  {% endblock %}
                </div>
                <div class="large-container disqus-container">
                    {% include 'disqus_comments.html' %}
                </div>
            </div>
        </div>

    </div>

{% endblock %}


{% block extra_attribution %}
  {# If the object has a summary it may have come from Wikipedia. Display the attribution. #}
  {% if object.summary %}
    {% include 'wikipedia_attribution.html' %}
  {% endif %}
  {# Display any attribution for candidate data #}
  {% include 'candidate_data_attribution.html' %}
{% endblock %}

pombola/kenya/templates/core/person_appearances.html
{% extends 'core/person_base.html' %}
{% load url from future %}

{% block title %}{{ object.name }} Appearances{% endblock %}

{% block subcontent %}

  {% if settings.ENABLED_FEATURES.hansard %}

      {% with hansard_count=object.hansard_entries.count %}
            {% if hansard_count %}

              <h2>Parliamentary appearances</h2>

              <p>{{ person.name }} has spoken {{ hansard_entries.count }} times in Parliament.</p>

              <h3>Recent Appearances</h3>

              <div id="appearances" data-url="{% url "hansard:person_summary" slug=object.slug %}">
                {% include 'core/person_detail_appearance_list.html' %}
              </div>

              <p>(<a href="{% url "hansard:person_appearances_all" slug=person.slug %}">View all speeches.</a>)</p>

              <h3>Lifetime summary</h3>

              <p>{{ person.name }} has month by month spoken in parliament this many times (if a month is missing there were no speeches found for that month):</p>

              <ul>
                {% for summary in lifetime_summary %}
                  <li>{{ summary.date|date:"M Y" }}: {{ summary.count }} speeches</li>
                {% endfor %}
              </ul>

            {% else %}
              <div>
                <p>{{ object.name }} has never spoken in Parliament.</p>
              </div>
            {% endif %}

      {% endwith %}
  {% else %}

    No appearances were found.
  {% endif  %}

{% endblock %}

pombola/kenya/templates/core/person_base.html
{% extends 'core/object_base.html' %}
{% load thumbnail %}
{% load url from future %}
{% load switch %}

{% block title %}{{ object.name }}{% endblock %}

{% block object_menu_links %}{% endblock %}

{% block object_tagline %}
  {% if object.is_politician %}
      {{ object.summary }}
  {% endif %}

  {% if object.is_aspirant %}
      <p>
          Aspirant in the upcoming elections:
          {% for aspiration in object.aspirant_positions %}
              {{ aspiration.title }}
              {% if not forloop.last %}, {% endif %}
          {% endfor %}
      </p>

      <p>
        Have information to add to our site about this aspirant?
        <a  href="{% url "feedback_add" %}?url={{ request.build_absolute_uri }}"
            class="feedback_link"
        >Tell us!</a>
      </p>
  {% endif %}
{% endblock %}

{% block profile_info %}

  {% if shujaaz_finalist %}
  <div class="object-sidebar__box awards">
    <h3>People’s Shujaaz Awards</h3>
    <p><a href="{% url 'shujaaz-finalists' %}#nominees">Finalist: {{ shujaaz_finalist.category }}</a></p>
  </div>
  {% endif %}

  <div class="object-sidebar__box constituency-party">

      {% if object.aspirant_constituencies.count %}
          <h3>Aspirant for</h3>
          <ul>
              {% for constituency in object.aspirant_constituencies %}
                  <li><a href="{{ constituency.get_absolute_url }}">{{ constituency.name }}</a></li>
              {% endfor %}
          </ul>
      {% endif %}

      {% regroup object.constituencies|dictsort:"kind" by kind as constituency_groups %}
      {% for entry in constituency_groups %}
      <h3>{{ entry.grouper }}</h3>
      <ul>
          {% for area in entry.list %}
              <li><a href="{{ area.get_absolute_url }}">{{ area.name }}</a></li>
          {% endfor %}
      </ul>
      {% endfor %}

      <h3>Parties &amp; Coalitions</h3>
      <ul>
          {% for party in object.parties_and_coalitions %}
              <li><a href="{{ party.get_absolute_url }}">{{ party.name }}</a></li>
          {% empty %}
              <li>Not a member of any parties or coalitions</li>
          {% endfor %}
      </ul>
  </div>

  {% if object.name != object.legal_name or object.contacts.count %}
  <div class="object-sidebar__box contact-details">
      {% if object.name != object.legal_name %}
          <h3>Full name</h3>
          <p>{{ object.legal_name }}</p>
      {% endif %}

      {% if object.date_of_birth %}
          <h3>Born</h3>
          <p>{{ object.date_of_birth }}</p>
      {% endif %}

      {% if object.date_of_death %}
          <h3>Died</h3>
          <p>{{ object.date_of_death }}</p>
      {% endif %}

      {# Simplified version of core/templates/core/contact_list.html #}
      {% if object.contacts.count %}
      {% for c in object.contacts.all %}
          {% switch c.kind.slug %}

              {% case 'phone' %}
                  <h3>Telephone</h3>
                  <p><a href="tel:{{ c.value }}">{{ c.value }}</a></p>

              {% case 'facebook' %}
                  <h3>Link</h3>
                  <p><a href="{{ c.value }}">{{ c.kind.name }}</a></p>

              {% case 'twitter' %}
                  <h3>Link</h3>
                  <p><a href="http://twitter.com/{{ c.value }}">@{{ c.value }}</a> on Twitter</p>

              {% case 'address' %}
                  <h3>Post</h3>
                  <p class="contact-details-address">{{ c.value|urlizetrunc:50 }}</p>

              {% else %}
                  <h3>{{ c.kind.name }}</h3>
                  <p>{{ c.value|urlizetrunc:50 }}</p>

          {% endswitch %}
          {% if c.notes %}
              <p>({{ c.notes }})</p>
          {% endif %}
      {% endfor %}
      {% endif %}
  </div>
  {% endif %}

{% endblock %}

pombola/kenya/templates/core/person_bills.html
{% extends 'core/person_base.html' %}
{% load url from future %}

{% block title %}{{ object.name }} Bills Sponsored{% endblock %}

{% block subcontent %}

  {% if settings.ENABLED_FEATURES.bills %}
    {% with object.bills_sponsored.count as bills_count %}
      {% if bills_count %}
        <h2>Bills Sponsored</h2>

        <p>{{ object.name }} has sponsored {{ bills_count }} bill{{ bills_count|pluralize }}.</p>
        {% regroup object.bills_sponsored.all by parliamentary_session as bills_regrouped %}
        {% for bills in bills_regrouped %}
          <h3>{{ bills.grouper.name }}</h3>
          <ul>
            {% for bill in bills.list %}
              <li>
                {% include "bills/_bill_link.html" %}
              </li>
            {% endfor %}
          </ul>
        {% endfor %}
      {% else %}
          <p>{{ object.name }} has never sponsored a bill.</p>
      {% endif %}
    {% endwith %}
  {% else %}
    No sponsored bills were found.
  {% endif  %}
{% endblock %}

pombola/kenya/templates/core/person_detail.html
{% extends 'core/person_base.html' %}
{% load url from future %}

{% block title %}{{ object.name }} Overview{% endblock %}

{% block subcontent %}

  <div class="person-detail-experience">
    <h2><a href="{% url "person_experience" slug=object.slug %}">Experience</a></h2>
    {% include 'core/person_detail_experience_list.html' with positions=object.position_set.all.political.currently_active %}
    <a href="{% url "person_experience" slug=object.slug %}">See full experience</a>
  </div>

  {% if settings.ENABLED_FEATURES.hansard %}
    {% with hansard_count=object.hansard_entries.count %}
      {% if hansard_count %}
      <div class="person-detail-hansard">
        <h2><a href="{% url "person_appearances" slug=object.slug %}">Parliamentary appearances</a></h2>
        {% include 'core/person_detail_appearance_list.html' %}
        <a href="{% url "person_appearances" slug=object.slug %}">See all {{ hansard_count }} appearances</a>
      </div>
      {% endif %}
    {% endwith %}
  {% endif %}

  {% if cdf_budget_constituencies %}
    <div class="person-detail-cdf-budgets">
      <h3>Constituencies Development Fund Budget</h3>
      {% for cdf_constituency in cdf_budget_constituencies %}
        <p><a href="{{ constituency.get_absolute_url }}">{{ cdf_constituency.constituency.name }}</a>, {{ cdf_constituency.budget.budget_session }}: <b>{{ cdf_constituency.budget.formatted_value }}</b></p>
      {% endfor %}
    </div>
  {% endif %}


  {% if settings.ENABLED_FEATURES.bills %}
    {% include "bills/_person_recent_bills.html" %}
  {% endif %}

{% endblock %}

pombola/kenya/templates/core/person_detail_appearance_list.html
{% load switch %}
{% load url from future %}

<ul>
  {% for entry in hansard_entries|slice:hansard_entries_to_show %}
    <li class="appearance">
      <h4><a href="{{ entry.get_absolute_url }}">{{ entry.content|truncatewords:20 }}</a></h4>
      <p class="appearance-date">{{ entry.sitting.venue.name }}, {{ entry.sitting.start_date}}</p>
    </li>
  {% endfor %}
</ul>

pombola/kenya/templates/core/person_detail_experience_list.html
{% load switch %}
{% load url from future %}

<ul>
{% for position in positions %}
    <li class="position {% if position.is_ongoing %}ongoing{% endif %}">
        <h4>
            {% if position.title.slug == 'mp' %}
                Member of <a href="{% url "organisation" 'parliament' %}">Parliament</a>
            {% else %}
                {{ position.title }}
            {% endif %}
            {% if position.organisation.slug == "parliament" and position.category == 'political' %}
                {# pass #}
            {% else %}
                of <a href="{{ position.organisation.get_absolute_url }}">{{ position.organisation.name }}</a>
            {% endif %}
            {% if position.place %}
                for <a href="{{ position.place.get_absolute_url }}">{{ position.place.name }}</a>
            {% endif %}
        </h4>

        {% if position.subtitle %}
            <p class="position-subtitle">({{ position.subtitle }})</p>
        {% endif %}

        <p class="position-date">{{ position.display_dates|safe }}</p>

        {% if position.note %}
            <p class="position-note">{{ position.note }}</p>
        {% endif %}
    </li>
{% empty %}
    <li>No records found.</li>
{% endfor %}
</ul>

pombola/kenya/templates/core/person_feature.html
{% load thumbnail %}

<div class="featured-person clearfix">
    <a href="{{ featured_person.get_absolute_url }}">
        {% thumbnail featured_person.primary_image "200x200" as im %}
            <img src="{{ im.url }}" alt="{{ featured_person.name }}" width="{{ im.width }}" height="{{ im.height }}" />
        {% empty %}
            <img src="{{STATIC_URL}}images/person-200x200.jpg" />
        {% endthumbnail %}
    </a>
    <div class="featured-person-info">
        <h2><a href="{{ featured_person.get_absolute_url }}">{{ featured_person.title }}{{ featured_person.name }}</a></h2>

        {% if featured_person.is_politician %}
        <p class="feature-person-role">Politician</p>
        {% endif %}

        <div class="feature-person-summary">
            {{ featured_person.summary|truncatewords_html:35 }}
        </div>
        {% comment %}
            Note it is odd for a featured person to not have a scorecard, simply because this is shown
            on the home page as "MP RATINGS" -- so admin should be careful to only tick "can_be_featured"
            for Person instances that are both indeed MPs and rated. This case is handled here, but
            really it's inappropriate to be featuring such a Person.
        {% endcomment %}
        {% if featured_person.show_overall_score and featured_person.has_scorecards %}
            <div class="rating-container">
                <div class="rating">
                    <a href="{{ featured_person.get_absolute_url }}">
                        Mzalendo Rating:
                        <strong>{{ featured_person.scorecard_overall_as_word|capfirst }}</strong>
                    </a>
                </div>
                {%if featured_person.has_scorecards %}
                    <a class="rating-img {{ featured_person.scorecard_overall_as_word }}" href="{{ featured_person.get_absolute_url }}"></a>
                {% endif %}
            </div>
        {% endif %}

        <div class="feature-nav">
            <a class="feature-prev" href="/?before={{ featured_person.slug }}">previous</a>
            <a class="feature-next" href="/?after={{ featured_person.slug }}">next</a>
        </div>
    </div>
</div>